endpoints:
  - name: reth-prysm
    rpc_url: "http://127.0.0.1:58723"
    socket: "ws://127.0.0.1:58724"
  - name: geth-lodestar
    rpc_url: "http://127.0.0.1:58728"
    socket: "ws://127.0.0.1:58729"
  - name: nethermind-teku
    rpc_url: "http://127.0.0.1:58733"
    socket: "ws://127.0.0.1:58734"
beacon_sse_url: 'http://127.0.0.1:52566' # FOCIL Enabled bean api endpoint. Leave blank if not needed
polling:
  interval: 0.1s
  timeout: 5s
filters:
  min_gas_price: 1gwei
log_level: "info"
