name: Docker Build & Push

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_TAG: ${{ github.head_ref || github.ref_name || github.ref }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Sanitize branch name for Docker tag
        id: sanitize
        run: |
          BRANCH_TAG="${DOCKER_TAG//\//-}"
          echo "BRANCH_TAG=$BRANCH_TAG" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            punkhazardlabs/txpool-viz:${{ env.BRANCH_TAG }}
            ${{ env.BRANCH_TAG == 'main' && 'punkhazardlabs/txpool-viz:latest' || '' }}
